# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: {{.Values.service.backend.port}}
    targetPort: {{.Values.service.backend.port}}
