# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: {{.Values.service.backendDeployment.ports.inContainerPort}}
    targetPort: {{.Values.service.backendDeployment.ports.outContainerPort}}
