apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bubbels-server.fullname" . }}-frontend-deployment
  labels:
  {{- include "bubbels-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontendDeployment.replicas }}
  selector:
    matchLabels:
      app: frontend
    {{- include "bubbels-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: frontend
      {{- include "bubbels-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.frontendDeployment.angular.image.repository }}:{{ .Values.frontendDeployment.angular.image.tag
          | default .Chart.AppVersion }}
        name: angular
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bubbels-server.fullname" . }}-backend-deployment
  labels:
  {{- include "bubbels-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backendDeployment.replicas }}
  selector:
    matchLabels:
      app: backend
    {{- include "bubbels-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: backend
      {{- include "bubbels-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.backendDeployment.backend.image.repository }}:{{ .Values.backendDeployment.backend.image.tag
          | default .Chart.AppVersion }}
        name: backend
        ports:
        - containerPort: 8080
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bubbels-server.fullname" . }}-mysql
  labels:
  {{- include "bubbels-server.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.mysql.strategy.type | quote }}
  selector:
    matchLabels:
      app: mysql
    {{- include "bubbels-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mysql
      {{- include "bubbels-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ quote .Values.mysql.mysql.env.mysqlRootPassword }}
        - name: MYSQL_DATABASE
          value: {{ quote .Values.mysql.mysql.env.mysqlDatabase }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mysql.mysql.image.repository }}:{{ .Values.mysql.mysql.image.tag
          | default .Chart.AppVersion }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "bubbels-server.fullname" . }}-mysql-pv-claim
