apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bubbels-server.fullname" . }}-example-ingress
  labels:
  {{- include "bubbels-server.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: b.local.shopware.beer
    http:
      paths:
      - backend:
          service:
            name: '{{ include "bubbels-server.fullname" . }}-frontend'
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: api.local.shopware.beer
    http:
      paths:
      - backend:
          service:
            name: '{{ include "bubbels-server.fullname" . }}-backend'
            port:
              number: 8080
        path: /
        pathType: Prefix
