# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: {{.Values.backendDeployment.ports.inContainerPort}}
    targetPort: {{.Values.backendDeployment.ports.outContainerPort}}