apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  ingressClassName: nginx   
  rules:
  - host: {{.Values.frontendDeployment.url}}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: frontend
            port:
              number: {{.Values.frontendDeployment.ports.outContainerPort}}
  - host: {{.Values.backendDeployment.url}}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: backend
            port:
              number: {{.Values.backendDeployment.ports.outContainerPort}}