apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bubbels-server.fullname" . }}-mysql-pv-claim
  labels:
  {{- include "bubbels-server.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mysqlPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.mysqlPvClaim.storageClass | quote }}
